[package]
name = "aoc25"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc_common = { path = "../aoc_common" }
anyhow = "1.0.75"
colored = "2.0.4"
itertools = "0.12.0"
num = "0.4.1"
divisors = "0.2.1"
regex = "1.11.1"
rayon = "1.11.0"

